FROM python:3.12

WORKDIR /server

ADD . /server

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install "fastapi[standard]"

CMD ["python", "-m", "fastapi", "run", "main.py", "--host", "127.0.0.1", "--port", "5050"]