FROM python:3.12

WORKDIR /server

ADD . /server

ENV OPENAI_API_KEY ${OPENAI_API_KEY}
ENV TWILIO_ACCOUNT_SID ${TWILIO_ACCOUNT_SID}
ENV TWILIO_AUTH_TOKEN ${TWILIO_AUTH_TOKEN}
ENV MYSQL_DB ${MYSQL_DB}
ENV MYSQL_USER ${MYSQL_USER}
ENV MYSQL_PASSWORD ${MYSQL_PASSWORD}
ENV MYSQL_HOST ${MYSQL_HOST}
ENV MYSQL_PORT ${MYSQL_PORT} 

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install "fastapi[standard]"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]